# Generated by Django 3.1.7 on 2021-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_manager_police_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='muni_cert',
            field=models.FileField(blank=True, null=True, upload_to='municerts/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='police_cert',
            field=models.FileField(blank=True, null=True, upload_to='policerts/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/%Y/%m/%D/'),
        ),
    ]
