# Generated by Django 3.1.7 on 2021-05-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gangrp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
