# Generated by Django 3.1.7 on 2021-05-30 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_video_gangrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gangrp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.gangroup'),
        ),
    ]
