# Generated by Django 3.1.7 on 2021-05-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210411_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='gangroups',
            field=models.ManyToManyField(to='users.GanGroup'),
        ),
    ]
