# Generated by Django 3.1.7 on 2021-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210411_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
