# Generated by Django 3.1.7 on 2021-05-04 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210504_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gangroup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='gangroups',
        ),
        migrations.AddField(
            model_name='gangroup',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
