# Generated by Django 3.1.7 on 2021-06-01 19:58

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210530_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='gallery/', validators=[users.validators.file_size])),
                ('gangrp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
