# Generated by Django 3.1.7 on 2021-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
