# Generated by Django 3.1.7 on 2021-05-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210504_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gangroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gangroup',
            name='member',
        ),
        migrations.AddField(
            model_name='gangroup',
            name='member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
    ]
