# Generated by Django 3.1.7 on 2021-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210429_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
