# Generated by Django 3.1.7 on 2021-05-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210504_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gangroup',
            name='member',
        ),
        migrations.AddField(
            model_name='gangroup',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gangroups',
            field=models.ManyToManyField(to='users.GanGroup'),
        ),
    ]
