# Generated by Django 3.1.7 on 2021-05-04 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210504_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangroup',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='gangroup',
            name='member',
        ),
        migrations.AddField(
            model_name='gangroup',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gangroup',
            name='name',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
    ]
