# Generated by Django 3.1.7 on 2021-05-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210505_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gangroup',
            options={},
        ),
    ]
