# Generated by Django 3.1.7 on 2021-05-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210429_2116'),
        ('users', '0008_auto_20210504_0334'),
    ]

    operations = [
    ]
