# Generated by Django 3.1.7 on 2021-05-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210429_2116'),
        ('users', '0009_auto_20210505_1747'),
    ]

    operations = [
    ]
