# Generated by Django 3.1.7 on 2021-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20210525_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gangroup',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
