# Generated by Django 3.1.7 on 2021-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210525_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
