pipeline {
    agent { docker { image 'python:3.8-buster' } }
    triggers {
      githubPush()
  }

    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }

        }
        stage('setup'){
          steps{
            withEnv(["HOME=${env.WORKSPACE}"]){

            dir('jenkins'){
            sh 'python -m pip install -r requirements.txt'
            }
            echo 'hello'
          }
          }
        }

          stage('Run Unit Tests') {
                steps {
            dir("ganMoodle_project") {
              withEnv(["HOME=${env.WORKSPACE}"]) {
                sh "python -m coverage run manage.py test --tag=unit-test"

              }
            }
          }
            }
    }

}
