pipeline {
    agent { docker { image 'python:3.8-buster' } }
    triggers {
      githubPush()
  }

    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }

        }
    stage('Migrate') {
        steps{
          dir("GanMoodle") {
            withEnv(["HOME=${env.WORKSPACE}"]) {
                sh 'python manage.py makemigrations'
                sh 'python manage.py migrate'
            }
          }
        }
      }
        stage('setup'){
          steps{
            withEnv(["HOME=${env.WORKSPACE}"]){

            dir('jenkins'){
            sh 'python -m pip install -r requirements.txt'
            }
            echo 'hello'
          }
          }
        }

        stage('Run Unit Tests') {
                steps {
    				dir("GanMoodle") {
    					withEnv(["HOME=${env.WORKSPACE}"]) {
    						sh "python -m coverage run manage.py test --tag=unit-test"
    					}
    				}
    			}
            }

          stage('coverage') {

              steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    dir("Agile_inv") {
                       sh 'python -m coverage run manage.py test'
                       sh 'python -m coverage report --fail-under=81'

                    }
        }
        }
    }
        stage('pylint') {

              steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                      dir("Agile_inv") {
                          sh 'pip install pylint'
                          sh 'pip install pylint-django'
                          sh 'python -m  pylint  --fail-under=8  Agile_inv sprint userStory login project msgAdmin'
                      }

                }
              }
        }
    }
    post {
        failure{
          mail to: 'B7FunService@gmail.com',
          subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
          body: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
        }
        success{
          mail to: 'B7FunService@gmail.com',
          subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
          body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
        }
    }
  }
