pipeline {
    agent { docker { image 'python:3.8-buster' } }
    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }
        }
        stage('setup'){
          steps{
            sh 'python -m pip install -r requirements.txt'
            sh 'echo hello'
          }
        }
    }
}
